# Generated by Django 3.0.8 on 2020-08-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='follower_id',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='followers',
            old_name='user_id',
            new_name='user',
        ),
    ]
